import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Banner from "@/components/Banner";
import Skills from "@/components/Skills";
import { NextPage } from "next";
import Projects from "@/components/Projects";
import Contact from "@/components/Contact";
import Wrapper from "@/components/Wrapper";

const inter = Inter({ subsets: ["latin"] });

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper>
        <Header />
        <Banner />
        <Projects />
        <Skills />
        <Contact />
      </Wrapper>
    </>
  );
};
export default Home;
